version: '3.8'
services:
  skinny:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/devp:ubuntu-skinny
    build:
      context: .
      target: devp_skinny
      args: 
      - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ~/
      target: /home/devel

  phat:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/devp:ubuntu-phat
    build:
      context: .
      target: devp_phat
      args: 
      - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ~/
      target: /home/devel
  
  phatt:
    entrypoint:
    - sleep
    - infinity
    image: kindtek/devp:ubuntu-phatt
    build:
      context: .
      target: devp_phatt
      args: 
      - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock
    - type: bind
      source: ~/
      target: /home/devel

