version: '3.8'
name: devels-workshop-ubuntu
services:
  git:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-git
    build:
      context: .
      target: devp_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  phat:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-phat
    build:
      context: .
      target: devp_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  phattest:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-phattest
    build:
      context: .
      target: devp_phattest
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  phatso:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-phatso
    build:
      context: .
      target: devp_phatso
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
