version: '3.8'
# name: devels-workshop-ubuntu
services:
  # skel:
  #   entrypoint:
  #     - sleep
  #     - infinity
  #   image: kindtek/dplay:ubuntu-skel
  #   build:
  #     context: .
  #     target: dplay_skel
  #     args:
  #       - username=${username:-gabriel}
  #     dockerfile: dockerfile.ubuntu.yaml
  #   init: true
  #   volumes:
  #     - hel-data:/mnt/w
  #     # - type: volume
  #     #   source: hel-data
  #     #   target: /home/devel
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock
  #     - type: bind
  #       source: ~/
  #       target: /home/host
  git:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-git
    build:
      context: .
      target: dplay_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - hel-data:/mnt/w
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  phat:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-phat
    build:
      context: .
      target: dplay_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - hel-data:/mnt/w
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  phatter:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-phatter
    build:
      context: .
      target: dplay_phatter
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - hel-data:/mnt/w
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  phattest:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-phattest
    build:
      context: .
      target: dplay_phattest
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - hel-data:/mnt/w
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  # phatso:
  #   entrypoint:
  #     - sleep
  #     - infinity
  #   image: kindtek/dplay:ubuntu-phatso
  #   build:
  #     context: .
  #     target: dplay_phatso
  #     args:
  #       - username=${username:-gabriel}
  #     dockerfile: dockerfile.ubuntu.yaml
  #   init: true
  #   volumes:
  #     - hel-data:/mnt/w
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock
  #     - type: bind
  #       source: ~/
  #       target: /home/host

volumes:
  hel-data:
    external: false
