version: "3.9"
name: devels-workshop-ubuntu
services:
  # chown-hel:
  #   # Need a user priviliged enough to chown
  #   user: 'root'
  #   # Specify the group in question
  #   group_add:
  #     - 'devels'
  #   volumes:
  #     # The volume to chown
  #     - hel-data:/tmp/change-ownership
  #   command: chown -R devel:devels /tmp/change-ownership
  skel:
    # Need a user priviliged enough to chown
    user: gabriel
    # Specify the group in question
    group_add:
      - host
      - archans
      - devels
    # image: kindtek/dplay:ubuntu-skel
    build:
      context: .
      target: dplay_skel
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
      # network: ${COMPOSE_PROJECT_NAME}_default
    init: true
    volumes:
      - hel-data:/tmp/devel
    command: chown -R devel:devels /tmp/devel
    labels:
      com.dplay_skel.description: "n/a"


  git:
    # owner/group becomes owner of hel-data volume
    user: devel
    group_add:
      # - archans
      - devels 
    privileged: true
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dplay_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      skel:
        # Wait for the ownership to change
        condition: service_completed_successfully
    volumes:
      - hel-data:/home/devel
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    labels:
      com.dplay_git.description: "basics + git"

  phat:
    extends: git
    image: kindtek/dplay:ubuntu-phat
    build:
      context: .
      target: dplay_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_phat.description: "basics + git + powerhell"
  phatter:
    extends: phat
    image: kindtek/dplay:ubuntu-phatter
    build:
      context: .
      target: dplay_phatter
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_phatter.description: "basics + git + powerhell + docker"
  phattest:
    extends: phatter
    image: kindtek/dplay:ubuntu-phattest
    build:
      context: .
      target: dplay_phattest
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_phattest.description: "basics + git + powerhell + docker + gui"
  phatso:
    extends: phattest
    image: kindtek/dplay:ubuntu-phatso
    build:
      context: .
      target: dplay_phatso
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
      labels:
        com.dplay_phatso.description: "basics + git + powerhell + docker + gui + cuda"
volumes:
  hel-data:


networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true

