version: "3.8"
services:
  alpine-build:
    build:
      context: .
      dockerfile: docker-compose.alpine.yaml
  ubuntu-build:
    build:
      context: .
      dockerfile: docker-compose.ubuntu.yaml
