version: "3.9"
name: devels-workshop-ubuntu
services:
  # chown-hel:
  #   # Need a user priviliged enough to chown
  #   user: 'root'
  #   # Specify the group in question
  #   group_add:
  #     - 'horns'
  #   volumes:
  #     # The volume to chown
  #     - hel-data:/tmp/change-ownership
  #   command: chown -R devel:horns /tmp/change-ownership
  skel:
    # Need a user priviliged enough to chown
    user: gabriel
    # image: kindtek/dplay:ubuntu-skel
    build:
      context: .
      target: dplay_skel
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
      # network: ${COMPOSE_PROJECT_NAME}_default
    init: true
    volumes:
      - hel-data:/tmp/devel
    command: sudo chown -R devel:horns /tmp/devel
    labels:
      com.dplay_skel.description: "n/a"

  data:
    user: gabriel
    build:
      context: .
      target: dplay_data
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - hel-data:/mnt/w
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    labels:
      com.dplay_data.description: "shared backup drive"
    depends_on:
      skel:
        # Wait for the ownership to change
        condition: service_completed_successfully

  git:
    # owner/group becomes owner of hel-data volume
    user: devel
    group_add:
      # - halos
      - horns
    privileged: true
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dplay_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      skel:
        # Wait for the ownership to change
        condition: service_completed_successfully
    volumes:
      - hel-data:/home/devel
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    labels:
      com.dplay_git.description: "basics + git"
  phell:
    extends: git
    image: kindtek/dplay:ubuntu-phell
    build:
      context: .
      target: dplay_phell
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_phell.description: "basics + git + powerhell"
  dind:
    extends: phell
    image: kindtek/dplay:ubuntu-dind
    build:
      context: .
      target: dplay_dind
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_dind.description: "basics + git + powerhell + docker"
  gui:
    extends: dind
    image: kindtek/dplay:ubuntu-gui
    build:
      context: .
      target: dplay_gui
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_gui.description: "basics + git + powerhell + docker + gui"
  cuda:
    extends: gui
    image: kindtek/dplay:ubuntu-cuda
    build:
      context: .
      target: dplay_cuda
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
      labels:
        com.dplay_cuda.description: "basics + git + powerhell + docker + gui + cuda"

volumes:
  hel-data:


networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
