version: "3.9"
name: devels-workshop-ubuntu
services:
  initialize:
    # Need a user priviliged enough to chown
    build:
      context: .
      target: dplay_init
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    command:
      - bin/bash
      - -c
      - export _GABRIEL=${_GABRIEL:-gabriel}
      - export _HALOS=${_HALOS:-halos}
      - ln -s /home/${_GABRIEL:-gabriel} /tmp/${_GABRIEL:-gabriel} 
      - ln -s /home/devel /tmp/devel
      - mkdir -p /mnt/data 
      - ln -s /mnt/data /tmp/data 

    # command: echo something
  chown-halo:
    # Need a user priviliged enough to chown
    user: ${_GABRIEL:-gabriel}
    # Specify the wings in question
    group_add:
      - ${_HALOS:-halos}
    build:
      context: .
      target: dplay_halo
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      initialize:
        # Wait for the groups to be added
        condition: service_completed_successfully
    init: true
    volumes:
      - halo-data:/tmp/${_GABRIEL:-gabriel}
    command: sudo chown -R ${_GABRIEL:-gabriel}:${_HALOS:-halos} /tmp/${_GABRIEL:-gabriel}

  chown-hel:
    # Need a user priviliged enough to chown
    user: devel
    # Specify the wings in question
    group_add:
      - horns
    build:
      context: .
      target: dplay_hel
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      initialize:
        # Wait for groups to be added
        condition: service_completed_successfully
    init: true
    volumes:
      - hel-data:/tmp/devel
    command: chown -R devel:horns /tmp/devel
  data:
    user: ${_GABRIEL:-gabriel}
    group_add:
      - ${_HALOS:-halos}
    build:
      context: .
      target: dplay_data
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      chown-hel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      chown-halo:
        # Wait for the ownership to change
        condition: service_completed_successfully
    init: true
    volumes:
      - mnt-data:/tmp/data
    # command: 
    #   - chown -R ${_GABRIEL:-gabriel}:${_HALOS:-halos} /tmp/data
  skel:
    extends: data
    # Need a user priviliged enough to chown
    user: ${_GABRIEL:-gabriel}
    # image: kindtek/dplay:ubuntu-skel
    build:
      context: .
      target: dplay_skel
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
        - _HALOS=${_HALOS:-halos}
      dockerfile: dockerfile.ubuntu.yaml
      # network: ${COMPOSE_PROJECT_NAME}_default
    init: true
    volumes:
      - hel-data:/home/devel
      - halo-data:/home/${_GABRIEL:-gabriel}
      - mnt-data:/mnt/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

    depends_on:
      data:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.dplay_skel.description: "skeleton"

  git:
    # owner/group becomes owner of hel-data volume
    extends: data
    user: devel
    privileged: true
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dplay_git
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      chown-hel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      chown-halo:
        # Wait for the ownership to change
        condition: service_completed_successfully
      data:
        # Wait for the ownership to change
        condition: service_completed_successfully
    volumes:
      - hel-data:/home/devel
      - halo-data:/home/${_GABRIEL:-gabriel}
      - /mnt/data
    labels:
      com.dplay_git.description: "basics + git"

  python:
    extends: git
    image: kindtek/dplay:ubuntu-py
    build:
      context: .
      target: dplay_msdot
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_msdot.description: "basics + git + powerhell"

  msdot:
    extends: python
    image: kindtek/dplay:ubuntu-msdot
    build:
      context: .
      target: dplay_msdot
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_msdot.description: "basics + git + powerhell"
  dind:
    extends: msdot
    image: kindtek/dplay:ubuntu-dind
    build:
      context: .
      target: dplay_dind
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_dind.description: "basics + git + powerhell + docker"
  gui:
    extends: dind
    image: kindtek/dplay:ubuntu-gui
    build:
      context: .
      target: dplay_gui
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    labels:
      com.dplay_gui.description: "basics + git + powerhell + docker + gui"
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
  cuda:
    extends: gui
    image: kindtek/dplay:ubuntu-cuda
    build:
      context: .
      target: dplay_cuda
      args:
        - _GABRIEL=${_GABRIEL:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
      labels:
        com.dplay_cuda.description: "basics + git + powerhell + docker + gui + cuda"
volumes:
  hel-data:
  halo-data:
  mnt-data:
networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
  #     volumes:
  #       - type: bind
  #         source: home-vol
  #         target: /home
  #       - type: bind
  #         source: usr-vol
  #         target: /usr

  #     volumes:
  #       - bin-vol:/mnt/root_fs/bin
  #       - boot-vol:/mnt/root_fs/boot
  #       - dev-vol:/mnt/root_fs/dev
  #       - etc-vol:/mnt/root_fs/etc
  #       - halo-vol:/mnt/root_fs/halo
  #       - hel-vol:/mnt/root_fs/hel
  #       - home-vol:/mnt/root_fs/home
  #       - lib-vol:/mnt/root_fs/lib
  #       - lib32-vol:/mnt/root_fs/lib32
  #       - lib64-vol:/mnt/root_fs/lib64
  #       - libx32-vol:/mnt/root_fs/libx32
  #       - media-vol:/mnt/root_fs/media
  #       - mnt-vol:/mnt/root_fs/mnt
  #       - opt-vol:/mnt/root_fs/opt
  #       - proc-vol:/mnt/root_fs/proc
  #       - root-vol:/mnt/root_fs/root
  #       - run-vol:/mnt/root_fs/run
  #       - sbin-vol:/mnt/root_fs/sbin
  #       - srv-vol:/mnt/root_fs/srv
  #       - sys-vol:/mnt/root_fs/sys
  #       - tmp-vol:/mnt/root_fs/tmp
  #       - usr-vol:/mnt/root_fs/usr
  #       - var-vol:/mnt/root_fs/var
  # volumes:
  #   bin-vol:
  #   boot-vol:
  #   dev-vol:
  #   etc-vol:
  #   halo-vol:
  #   hel-vol:
  #   home-vol:
  #   lib-vol:
  #   lib32-vol:
  #   lib64-vol:
  #   libx32-vol:
  #   media-vol:
  #   mnt-vol:
  #   opt-vol:
  #   proc-vol:
  #   root-vol:
  #   run-vol:
  #   sbin-vol:
  #   srv-vol:
  #   sys-vol:
  #   tmp-vol:
  #   usr-vol:
  #   var-vol:



