version: "3.8"
name: devels-workshop-ubuntu
services:
  # chown-hel:
  #   # Need a user priviliged enough to chown
  #   user: 'root'
  #   # Specify the group in question
  #   group_add:
  #     - 'devels'
  #   volumes:
  #     # The volume to chown
  #     - hel-data:/tmp/change-ownership
  #   command: chown -R devel:devels /tmp/change-ownership
  skel:
    # Need a user priviliged enough to chown
    user: root
    # Specify the group in question
    group_add:
      - devels
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-skel
    build:
      context: .
      target: devp_skel
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      # - hel-data:/home/devel
      - hel-data:/tmp/change-ownership
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: chown -R devel:devels /tmp/change-ownership

  git:
    image: kindtek/devp:ubuntu-git
    extends: skel
    build:
      context: .
      target: devp_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      skel:
        # Wait for the ownership to change
        condition: service_completed_successfully
    # volumes:
    #   - hel-data:/home/devel
  phat:
    extends: git
    image: kindtek/devp:ubuntu-phat
    build:
      context: .
      target: devp_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml

  phatt:
    extends: phat
    image: kindtek/devp:ubuntu-phatt
    build:
      context: .
      target: devp_phatt
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml

  phatter:
    extends: phatt
    image: kindtek/devp:ubuntu-phatter
    build:
      context: .
      target: devp_phatter
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml

  phattest:
    extends: phatter
    image: kindtek/devp:ubuntu-phattest
    build:
      context: .
      target: devp_phattest
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
  phatso:
    extends: phattest
    image: kindtek/devp:ubuntu-phatso
    build:
      context: .
      target: devp_phatso
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
volumes:
  hel-data:
