version: '3.8'
name: devels-workshop-ubuntu
services:
  skinny:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:ubuntu-skinny
    build:
      context: .
      target: d2w_skinny
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  phat:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:ubuntu-phat
    build:
      context: .
      target: d2w_phat
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  phatt:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:ubuntu-phatt
    build:
      context: .
      target: d2w_phatt
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  phatter:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:ubuntu-phatter
    build:
      context: .
      target: d2w_phatter
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  # phattest:
  #   entrypoint:
  #     - sleep
  #     - infinity
  #   image: kindtek/d2w:ubuntu-phattest
  #   build:
  #     context: .
  #     target: d2w_phattest
  #     args:
  #       - username=${username:-dev0}
  #     dockerfile: dockerfile.ubuntu.yaml
  #   init: true
  #   volumes:
  #     - type: bind
  #       source: /var/run/docker.sock
  #       target: /var/run/docker.sock
  #     - type: bind
  #       source: ~/
  #       target: /home/host
