version: "3.8"
name: devels-workshop-ubuntu
services:
  # chown-hel:
  #   # Need a user priviliged enough to chown
  #   user: 'root'
  #   # Specify the group in question
  #   group_add:
  #     - 'devels'
  #   volumes:
  #     # The volume to chown
  #     - hel-data:/tmp/change-ownership
  #   command: chown -R devel:devels /tmp/change-ownership
  skel:
    # Need a user priviliged enough to chown
    user: root
    # Specify the group in question
    group_add:
      - devels
    image: kindtek/dplay:ubuntu-skel
    build:
      context: .
      target: dplay_skel
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
      # network: ${COMPOSE_PROJECT_NAME}_default
    init: true
    volumes:
      - hel-data:/tmp/devel
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: chown -R devel:devels /tmp/devel

  git:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dplay_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    depends_on:
      skel:
        # Wait for the ownership to change
        condition: service_completed_successfully
    volumes:
      - hel-data:/home/devel
  phat:
    extends: git
    image: kindtek/dplay:ubuntu-phat
    build:
      context: .
      target: dplay_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
  phattest:
    extends: phatter
    image: kindtek/dplay:ubuntu-phattest
    build:
      context: .
      target: dplay_phattest
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
  phatso:
    extends: phattest
    image: kindtek/dplay:ubuntu-phatso
    build:
      context: .
      target: dplay_phatso
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
volumes:
  hel-data:


networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
