version: "3.8"
name: devels-workshop-ubuntu
services:
  chown-hel:
    # Need a user priviliged enough to chown
    user: 'root'
    # Specify the group in question
    group_add:
      - 'devels'
    volumes:
      # The volume to chown
      - hel-data:/tmp/change-ownership
    command: chown -R devel:devels /tmp/change-ownership
  skinny:
    extends:  chown-hel
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-skinny
    build:
      context: .
      target: devp_skinny
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - hel-data:/home/devel
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      chown-hel:
        # Wait for the ownership to change
        condition: service_completed_successfully
  git:
    image: kindtek/devp:ubuntu-git
    extends: skinny
    build:
      context: .
      target: devp_git
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
  phat:
    extends: git
    image: kindtek/devp:ubuntu-phat
    build:
      context: .
      target: devp_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml

  phatt:
    extends: phat
    image: kindtek/devp:ubuntu-phatt
    build:
      context: .
      target: devp_phatt
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml

  phatter:
    extends: phatt
    image: kindtek/devp:ubuntu-phatter
    build:
      context: .
      target: devp_phatter
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml

  phattest:
    extends: phatter
    image: kindtek/devp:ubuntu-phattest
    build:
      context: .
      target: devp_phattest
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
  phatso:
    extends: phattest
    image: kindtek/devp:ubuntu-phatso
    build:
      context: .
      target: devp_phatso
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
volumes:
  hel-data:
