version: '3.8'
name: devels-workshop-alpine
services:
  skinny:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:alpine-skinny
    build:
      context: .
      target: d2w_skinny
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.alpine.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/devel

  phat:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:alpine-phat
    build:
      context: .
      target: d2w_phat
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.alpine.yaml

    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/devel
  phatt:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/d2w:alpine-phatt
    build:
      context: .
      target: d2w_phatt
      args:
        - username=${username:-dev0}
      dockerfile: dockerfile.alpine.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/devel
