version: '3.8'
name: devels-workshop-ubuntu
services:
  skel:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:ubuntu-skel
    build:
      context: .
      target: devp_skel
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  git:
    image: kindtek/devp:ubuntu-git
    extends: skel
    build:
      target: devp_git
  phat:
    extends: git
    image: kindtek/devp:ubuntu-phat
    build:
      target: devp_phat

  phatt:
    extends: phat
    image: kindtek/devp:ubuntu-phatt
    build:
      target: devp_phatt

  phatter:
    extends: phatt
    image: kindtek/devp:ubuntu-phatter
    build:
      target: devp_phatter

  phattest:
    extends: phatter
    image: kindtek/devp:ubuntu-phattest
    build:
      target: devp_phattest
  phatso:
    extends: phattest
    image: kindtek/devp:ubuntu-phatso
    build:
      target: devp_phatso
