version: '3.8'
name: devels-workshop-alpine
services:
  skel:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:alpine-skel
    build:
      context: .
      target: devp_skeleton
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.alpine.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host

  phat:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:alpine-phat
    build:
      context: .
      target: devp_phat
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.alpine.yaml

    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  phatt:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/devp:alpine-phatt
    build:
      context: .
      target: devp_phatt
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.alpine.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
