version: '3.8'
name: devels-workshop-ubuntu
services:
  skel:
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-skel
    build:
      context: .
      target: dplay_skel
      args:
        - username=${username:-gabriel}
      dockerfile: dockerfile.ubuntu.yaml
    init: true
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/
        target: /home/host
  git:
    image: kindtek/dplay:ubuntu-git
    extends: skel
    build:
      target: dplay_git
  msdot:
    extends: git
    image: kindtek/dplay:ubuntu-msdot
    build:
      target: dplay_msdot
  gui:
    extends: msdot
    image: kindtek/dplay:ubuntu-gui
    build:
      target: dplay_gui
  cuda:
    extends: gui
    image: kindtek/dplay:ubuntu-cuda
    build:
      target: dplay_cuda
