version: "3.9"
name: devels-playground-ubuntu
services:
  base:
    build:
      context: .
      target: dvlp_base
      # args: 
      #   - _AGL_USR=$_AGL
      #   - _DVL_USR=$_DVL
    init: true
    # command:
    # - /bin/bash
    # - -c
    # - export _AGL=agl
    # - export _HALO=${_HALO:-halo}
    # - sleep
    # - infinity
    # - ln -sf /home /mnt
    # - mkdir -p /mnt/data
    # - ln -sf /mnt/data /tmp/data
    # command: echo something
  base-god:
    # Need a user priviliged enough to chown
    user: root
    # Specify the wings in question
    group_add:
      - rootg
      - halo
      - hell
    build:
      context: .
      target: dvlp_base-god
    depends_on:
      base:
        condition: service_completed_successfully
    init: true
    # volumes:
    #   - god-data:/root:ro
    #   - gdi-data:/home/god
  base-angel:
    # Need a user priviliged enough to chown
    user: agl
    # Specify the wings in question
    group_add:
      - halo
    build:
      context: .
      target: dvlp_base-angel
    depends_on:
      base:
        condition: service_completed_successfully
    init: true
    # volumes:
    #   - hell-data:/home/agl
  base-devel:
    user: dvl
    group_add:
      - hell
    build:
      context: .
      target: dvlp_base-devel
    depends_on:
      base:
        # Wait for groups to be added
        condition: service_completed_successfully
    # volumes:
    #   - hell-data:/home/dvl
    init: true
  # alias(es) for agl
  # base-ausr:
  #   user: _AGL_USR
  #   extends: base-angel
  #   build:
  #     context: .
  #     target: dvlp_base-angel
  #     args:
  #       - _AGL_USR=${_AGL:-angel}
  #   volumes:
  #     - halo-data:/home/${_AGL_USR}
  #   init: true
  # # alias(es) for dvl
  # base-daus:
  #   user: _DVL_USR
  #   extends: init-dvl
  #   build:
  #     context: .
  #     target: dvlp_base-devel
  #     args:
  #       - _DVL_USR=${_DVL-:devel}
  #   volumes:
  #     - hell-data:/home/$_DVL_USR
  repo:
    user: agl
    group_add:
      - halo
    build:
      context: .
      target: dvlp_repo
    depends_on:
      base:
        # Wait for the ownership to change
        condition: service_completed_successfully
      base-god:
        # Wait for the ownership to change
        condition: service_completed_successfully
      base-angel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      base-devel:
        # Wait for the ownership to change
        condition: service_completed_successfully
    # # init: true
    # volumes_from:
    #   - base-angel
    #   - base-devel
    # volumes:
    #   - god-data:/root:ro
    #   - gdi-data:/home/god:rw
    #   - hell-data:/home/dvl
    #   # - hell-data:/home/devel
    #   # - hell-data:/home/${_DVL_USR:-dvl}
    #   # - halo-data:/home/${_AGL_USR:-agl}
    #   # - halo-data:/home/angel
    #   - halo-data:/home/agl
    #   - dls-data:/dls
    #   - mnt-data:/data
  skel-build:
    extends: repo
    user: agl
    tty: false
    build:
      context: .
      args:
        - _AGL=agl
        - _HALO=halo
      # network: ${COMPOSE_PROJECT_NAME}_default

      # init: true
      # volumes:
      #   - hell-data:/home/dvl
      #   - halo-data:/home/${_AGL:-agl}
      #   - mnt-data:/mnt/data
    depends_on:
      repo:
        # Wait for the ownership to change
        condition: service_completed_successfully
    # volumes:
    #   - mnt-data:/data
    #   # - hell-data:/home/${_DVL_USR:-dvl}
    #   - hell-data:/hel
    #   # - halo-data:/home/${_AGL_USR:-agl}
    #   - halo-data:/hal
    #   - gdi-data:/rootg

    labels:
      com.dvlp_skel.description: "-build skeleton"
  skel:
    extends: skel-build
    entrypoint:
      - sleep
      - infinity
    build:
      context: .
      target: dvlp_skel
    depends_on:
      skel-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    volumes:
      - mnt-data:/mnt/data
      # - hell-data:/home/${_DVL_USR:-dvl}
      - hell-data:/home/dvl
      # - halo-data:/home/${_AGL_USR:-agl}
      - halo-data:/home/agl
      - god-data:/home/god
    labels:
      com.dvlp_skel.description: "skeleton"
  bare:
    # owner/group becomes owner of hell-data volume
    extends: skel
    restart: on-failure
    tty: true
    # entrypoint:
    #   - sleep
    #   - infinity
    user: dvl
    working_dir: /home/dvl
    privileged: true
    image: kindtek/dvlp:ubuntu-bare
    # extends: skel
    build:
      context: .
      target: dvlp_bare
      args:
        - _AGL_USR=${_AGL:-agl}
        - mnt_data=${mnt_data:-/mnt/data}
        - _CONFIG_FILE
    depends_on:
      repo:
        # Wait for the ownership to change
        condition: service_completed_successfully
    init: true
    volumes:
      - hell-data:/hel
      - halo-data:/hal
      - gdi-data:/root:ro
      - god-data:/rootg
      - mnt-data:/mnt/data
      - dls-data:/mnt/data/dls
    labels:
      com.devels-playground.description: "basics + git"
  git-lite:
    # owner/group becomes owner of hell-data volume
    extends: bare
    image: kindtek/dvlp:ubuntu-git-lite
    # extends: skel
    build:
      context: .
      target: dvlp_git-lite
    labels:
      com.devels-playground.description: "basics + git"

  git:
    # owner/group becomes owner of hell-data volume
    extends: bare
    image: kindtek/dvlp:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dvlp_git
    labels:
      com.devels-playground.description: "basics + git"
  python-build:
    extends: bare
    build:
      context: .
      target: dvlp_python-build
    labels:
      com.devels-playground.description: "basics + git"
  python-build-lite:
    extends: bare
    build:
      context: .
      target: dvlp_python-build-lite
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.devels-playground.description: "basics + git"
  python-lite:
    extends: bare
    image: kindtek/dvlp:ubuntu-py-lite
    build:
      context: .
      target: dvlp_python-lite
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_started
    labels:
      com.devels-playground.description: "basics + git"
  python:
    extends: bare
    image: kindtek/dvlp:ubuntu-py
    build:
      context: .
      target: dvlp_python
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.devels-playground.description: "basics + git"
  msdot-lite:
    extends: bare
    image: kindtek/dvlp:ubuntu-msdot-lite
    build:
      context: .
      target: dvlp_msdot-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell"
  msdot:
    extends: bare
    image: kindtek/dvlp:ubuntu-msdot
    build:
      context: .
      target: dvlp_msdot
    labels:
      com.devels-playground.description: "basics + git + powerhell"
  dind:
    extends: bare
    image: kindtek/dvlp:ubuntu-dind
    build:
      context: .
      target: dvlp_dind
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker"
  kernel-lite:
    extends: bare
    image: kindtek/dvlp:ubuntu-kernel-lite
    build:
      context: .
      target: dvlp_kernel-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  kernel-builder:
    extends: bare
    image: kindtek/dvlp:ubuntu-kernel-builder
    build:
      context: .
      target: dvlp_kernel-builder
      args:
        - _CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  gui-lite:
    extends: bare
    # entrypoint: 
    #   - /bin/bash
    #   - -c
    #   - /home/dvl/start-kde.sh
    image: kindtek/dvlp:ubuntu-gui
    build:
      context: .
      target: dvlp_gui-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  gui:
    extends: gui-lite
    image: kindtek/dvlp:ubuntu-gui
    build:
      context: .
      target: dvlp_gui
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  gui-plus:
    extends: gui-lite
    image: kindtek/dvlp:ubuntu-gui-plus
    build:
      context: .
      target: dvlp_gui-plus
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  cuda:
    extends: gui-lite
    image: kindtek/dvlp:ubuntu-cuda
    build:
      context: .
      target: dvlp_cuda
      args:
        - _AGL_USR=${_AGL:-agl}
      labels:
        com.dvlp_cuda.description: "basics + git + powerhell + docker + gui + cuda"

  cuda-plus:
    extends: gui-lite
    image: kindtek/dvlp:ubuntu-cuda-plus
    build:
      context: .
      target: dvlp_cuda-plus
      args:
        - _AGL_USR=${_AGL:-agl}
      labels:
        com.dvlp_cuda.description: "basics + git + powerhell + docker + gui + cuda"
volumes:
  hell-data:
  halo-data:
  mnt-data:
  dls-data:
  god-data:
  gdi-data:


networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
