version: "3.9"
name: devels-playground-ubuntu
services:
  base:
    # user: good
    build:
      context: .
      target: dvlp_base-fs
      # args: 
      #   - _AGL_USR=$_AGL
      #   - _DVL_USR=$_DVL
    init: true
    volumes:
      # shared volumes but assign ownership
      # - repo_agl:/dvlw
      # - repo_dvl:/dvlw
      # - repo_good:/dvlw
      - root:/fs
      # - repo:/dvlw
      # - root_good:/fs
      # - root_agl:/fs
      # - root_dvl:/fs
      - dls:/dls
      - repo:/dvlw
      - home_agl:/hal
      - home_dvl:/hel
      - home_good:/root/root
      # - dls:/dls

      # command:
      # - /bin/bash
      # - -c
      # - export _AGL=agl
      # - export _HALO=${_HALO:-halo}
      # - sleep
      # - infinity
      # - ln -sf /home /mnt
      # - mkdir -p /mnt/data
      # - ln -sf /mnt/data /tmp/data
      # command: echo something
  base-good:
    # Need a user priviliged enough to chown
    # user: good
    # Specify the wings in question
    # group_add:
    #   - rootg
    #   - halo
    #   - hell
    build:
      context: .
      target: dvlp_base-fs_good
    depends_on:
      base:
        condition: service_completed_successfully
    init: true
    # volumes:
      # - repo:/dvlw
    #   - root:/root/root
  base-angel:
    # Need a user priviliged enough to chown
    # user: agl
    # Specify the wings in question
    # group_add:
    #   - halo
    build:
      context: .
      target: dvlp_base-fs_angel
    depends_on:
      base:
        condition: service_completed_successfully
    init: true
    # volumes:
    #   - home_agl:/hal
  base-devel:
    # user: dvl
    # group_add:
    #   - hell
    build:
      context: .
      target: dvlp_base-fs_devel
    depends_on:
      base:
        # Wait for groups to be added
        condition: service_completed_successfully
    # volumes:
    #   - home_dvl:/home/hel
    init: true
    # volumes:
    #   - home_dvl:/hel
    # alias(es) for agl
    # base-ausr:
    #   user: _AGL_USR
    #   extends: base-angel
    #   build:
    #     context: .
    #     target: dvlp_base-fs_angel
    #     args:
    #       - _AGL_USR=${_AGL:-angel}
    #   volumes:
    #     - home_agl:/home/${_AGL_USR}
    #   init: true
    # # alias(es) for dvl
    # base-daus:
    #   user: _DVL_USR
    #   extends: init-dvl
    #   build:
    #     context: .
    #     target: dvlp_base-fs_devel
    #     args:
    #       - _DVL_USR=${_DVL-:devel}
    #   volumes:
    #     - home_dvl:/home/$_DVL_USR
  repo:
    # user: good
    # group_add:
    #   - hell
    build:
      context: .
      target: dvlp_repo_build
    volumes:
      - repo:/dvlw
      # - root:/fs
      # - root_good:/fs
      # - root_agl:/fs
      # - root_dvl:/fs
      # - dls:/mnt/data/dls
    depends_on:
      base:
        # Wait for the ownership to change
        condition: service_completed_successfully
      base-good:
        # Wait for the ownership to change
        condition: service_completed_successfully
      base-angel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      base-devel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      # # init: true
      # volumes_from:
      #   - base-angel
      #   - base-devel
      # - repo_dvl:/hel/dvlw
      #   - root:/hell
      #   - home_good:/root:ro
      #   - root:/home/good:rw
      #   - home_dvl:/home/dvl
      #   # - home_dvl:/home/devel
      #   # - home_dvl:/home/${_DVL_USR:-dvl}
      #   # - home_agl:/home/${_AGL_USR:-agl}
      #   # - home_agl:/home/angel
      #   - home_agl:/home/agl
      # - dls:/dls
      #   - mnt-data:/data
  skel-build-lite:
    extends: repo
    # user: agl
    tty: false
    build:
      context: .
      args:
        - _AGL=agl
        - _HALO=halo
      # network: ${COMPOSE_PROJECT_NAME}_default
      # entrypoint: /bin/bash -c
      # # entrypoint: ["sudo chown -R agl:halo /home/agl/dvlw"]
      # command:
      #   - sudo chown -R agl:halo /hal
      #   - chown -R dvl:hell /hell
      # init: true
      # volumes:
      #   - home_dvl:/home/dvl
      #   - home_agl:/home/${_AGL:-agl}
      #   - mnt-data:/mnt/data
      # depends_on:
      #   skel:
      #     # Wait for the ownership to change
      #     condition: service_started
      # volumes:
      #   - root:/fs
      #   # - root:/hell
      #   - home_good:/home/good
      #   # - hell-data:/fs
      #   # - halo-data:/fs
      #   # # - home_dvl:/home/${_DVL_USR:-dvl}
      #   - home_dvl:/home/dvl
      #   # # - home_agl:/home/${_AGL_USR:-agl}
      #   - home_agl:/home/agl
      #   - repo_dvl:/home/dvl/dvlw
  skel-build:
    extends: skel-build-lite
    # volumes:
    #   - repo_agl:/home/agl/dvlw
    #   - repo_good:/home/good/dvlw
    labels:
      com.dvlp_skel.description: "-build skeleton"
  skel:
    user: good
    extends: skel-build
    entrypoint:
      - sleep
      - infinity
    # entrypoint: ["sudo chown -R agl:halo /home/agl/dvlw"]
    # command:
    # #   - sudo chown -R agl:halo /halo/hal/dvlw
    # #   - sudo chown -R dvl:hell /hell
    # #   # - sudo chown -R dvl:hell /hell
    #   - sleep infinity
    build:
      context: .
      target: dvlp_skel
      # depends_on:
      # bare:
      #   # Wait for the ownership to change
      #   condition: service_started
      # volumes:
      #   - hell-data:/hell
      #   - halo-data:/halo
      #   - mnt-data:/mnt/data
      #   # - home_dvl:/home/${_DVL_USR:-dvl}
      #   - home_dvl:/home/dvl
      #   # - home_agl:/home/${_AGL_USR:-agl}
      #   - home_agl:/home/agl
      #   - home_good:/home/good
    labels:
      com.dvlp_skel.description: "skeleton"
  bare:
    # owner/group becomes owner of home_dvl volume
    user: good
    extends: skel
    restart: on-failure
    tty: true
    entrypoint:
      - sleep
      - infinity
    working_dir: /hel
    privileged: true
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-bare
    # extends: skel
    build:
      context: .
      target: dvlp_bare
      args:
        - _AGL_USR=${_AGL:-agl}
        - mnt_data=${mnt_data:-/mnt/data}
        - CONFIG_FILE
    depends_on:
      base:
        # Wait for the ownership to change
        condition: service_completed_successfully
    init: true
    # entrypoint: ["sudo chown -R agl:halo /home/agl/dvlw"]
    # entrypoint: /bin/bash -c
    # # entrypoint: ["sudo chown -R agl:halo /home/agl/dvlw"]
    # # command:
    # #   # - sudo chown -R agl:halo /halo/hal/dvlw
    # #   # - chown -R dvl:hell 
    # #   # - sudo chown -R dvl:hell /hell
    # #   - sleep infinity
    # #   # - -c
    # #   # - sudo
    # #   # - chown 
    # #   # - -R 
    # #   # - agl:halo 
    # #   # - /halo/hal/dvlw
    volumes:
      - repo:/root/dvlw
      - repo_agl:/halo/hal/dvlw
      - repo_agl:/halo/dvlw
      - repo_agl:/hal/dvlw
      - repo_agl:/home/agl/dvlw

      - repo_dvl:/hell/hel/dvlw
      - repo_dvl:/hell/dvlw
      - repo_dvl:/hel/dvlw
      - repo_dvl:/home/dvl/dvlw

      - repo:/root/root/dvlw
      - repo_good:/dvlw
      - repo:/home/good/dvlw

      - root:/root
      - root_good:/fs
      - home_good:/root/root
      - home_good:/home/good

      - root_dvl:/hell
      - home_dvl:/hel
      - home_dvl:/hell/hel
      - home_dvl:/home/dvl

      - root_agl:/halo
      - home_agl:/hal
      - home_agl:/halo/hal
      - home_agl:/home/agl

      - mnt-data:/mnt/data

      - dls:/mnt/data/dls

      - dls_good:/dls
      - dls_good:/root/dls
      - dls_good:/root/root/dls
      - dls_good:/home/good/dls

      - dls_agl:/hal/dls
      - dls_agl:/halo/dls
      - dls_agl:/halo/hal/dls
      - dls_agl:/home/agl/dls

      - dls_dvl:/hel/dls
      - dls_dvl:/hell/dls
      - dls_dvl:/hell/hel/dls
      - dls_dvl:/home/dvl/dls
    labels:
      com.devels-playground.description: "basics + git"
  git-lite:
    # owner/group becomes owner of home_dvl volume
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-git-lite
    # extends: skel
    build:
      context: .
      target: dvlp_git-lite
    labels:
      com.devels-playground.description: "basics + git"

  git:
    # owner/group becomes owner of home_dvl volume
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dvlp_git
    labels:
      com.devels-playground.description: "basics + git"
  python-build:
    extends: bare
    build:
      context: .
      target: dvlp_python-build
    labels:
      com.devels-playground.description: "basics + git"
  python-build-lite:
    extends: bare
    build:
      context: .
      target: dvlp_python-build-lite
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.devels-playground.description: "basics + git"
  python-lite:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-py-lite
    build:
      context: .
      target: dvlp_python-lite
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_started
    labels:
      com.devels-playground.description: "basics + git"
  python:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-py
    build:
      context: .
      target: dvlp_python
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.devels-playground.description: "basics + git"
  msdot-lite:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-msdot-lite
    build:
      context: .
      target: dvlp_msdot-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell"
  msdot:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-msdot
    build:
      context: .
      target: dvlp_msdot
    labels:
      com.devels-playground.description: "basics + git + powerhell"
  dind:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-dind
    build:
      context: .
      target: dvlp_dind
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker"
  dind-lite:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-dind-lite
    build:
      context: .
      target: dvlp_dind-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  basic-wsl-kernel-builder:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-basic-wsl-kernel-builder
    build:
      context: .
      target: dvlp_basic-wsl-kernel-builder
      # args:
      #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  basic-wsl-zfs-kernel-builder:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:basic-wsl-zfs-kernel-builder
    build:
      context: .
      target: dvlp_basic-wsl-zfs-kernel-builder
      # args:
      #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  stable-wsl-zfs-kernel-builder:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:stable-wsl-zfs-kernel-builder
    build:
      context: .
      # target: dvlp_stable-wsl-zfs-kernel-builder
      # args:
      #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  latest-rc-wsl-zfs-kernel-builder:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:latest-rc-wsl-zfs-kernel-builder
    build:
      context: .
      target: dvlp_latest-rc-wsl-zfs-kernel-builder
      # args:
      #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  gui-lite:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-gui
    build:
      context: .
      target: dvlp_gui-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  gui:
    extends: bare
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-gui
    user: agl
    entrypoint:
      - /bin/bash
      - -c
      - bash /home/dvl/start-kde.sh
    build:
      context: .
      target: dvlp_gui
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  gui-plus:
    extends: gui-lite
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-gui-plus
    build:
      context: .
      target: dvlp_gui-plus
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  cuda:
    extends: gui-lite
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-cuda
    build:
      context: .
      target: dvlp_cuda
      args:
        - _AGL_USR=${_AGL:-agl}
      labels:
        com.dvlp_cuda.description: "basics + git + powerhell + docker + gui + cuda"

  cuda-plus:
    extends: gui-lite
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-cuda-plus
    build:
      context: .
      target: dvlp_cuda-plus
      args:
        - _AGL_USR=${_AGL:-agl}
      labels:
        com.dvlp_cuda.description: "basics + git + powerhell + docker + gui + cuda"
volumes:
  root:
  root_dvl:
  root_agl:
  root_good:

  mnt-data:

  dls:
  dls_dvl:
  dls_agl:
  dls_good:

  home_dvl:
  home_agl:
  home_good:

  repo:
  repo_agl:
  repo_dvl:
  repo_good:


networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
