version: "3.9"
name: devels-playground-ubuntu
services:
  repo-lite:
    build:
      target: dvlp_repo-lite
    volumes:
      - repo-lite:/dvlw
  repo:
    build:
      target: dvlp_repo
    volumes:
      - repo:/dvlw
  base:
    user: r00t
    build:
      target: dvlp_base-fs
      context: .
      args: 
        - _AGL=${_AGL_USR:-$_AGL}
        - _DVL=${_DVL_USR:-$_DVL}
        - _MNT=${_MNT:-/mnt/data}
        - CONFIG_FILE
    env_file:
      - .env
    # volumes:
    #   - dls:/dls
    init: true
    # init: true
    # depends_on:
    #   repo:
    #     condition: service_started
  base-r00t:
    extends: base
    build:
      target: dvlp_base-fs_r00t
  base-angel:
    extends: base
    build:
      target: dvlp_base-fs_angel
  base-devel:
    extends: base
    build:
      target: dvlp_base-fs_devel

    # alias(es) for agl
    # base-ausr:
    #   user: _AGL_USR
    #   extends: base-angel
    #   build:
    #     context: .
    #     target: dvlp_base-fs_angel
    #     args:
    #       - _AGL=${_AGL_USR:-$_AGL}
    #   volumes:
    #     - home_agl:/home/${_AGL_USR}
    #   init: true
    # # alias(es) for dvl
    # base-daus:
    #   user: _DVL_USR
    #   extends: init-dvl
    #   build:
    #     context: .
    #     target: dvlp_base-fs_devel
    #     args:
    #       - _DVL_USR=${_DVL-:devel}
    #   volumes:
    #     - home_dvl:/home/$_DVL_USR
  
  skel-build-lite:
    extends: base
    # user: agl
    tty: false
    build:
      target: dvlp_skel-build-lite
    volumes:
      - repo-lite:/dvlw
      - home_agl:/hal
      - home_agl:/home/${_AGL}
      - home_dvl:/hel
      - home_dvl:/home/${_DVL}
      - home_r00t:/r00t
      - home_r00t:/home/r00t
    depends_on:
        base:
            # Wait for the ownership to change
          condition: service_completed_successfully
    labels:
      com.dvlp_skel.description: "-build skeleton"

  skel-build:
    extends: base
    tty: false
    build:
      target: dvlp_skel-build
    volumes:
      - repo:/dvlw
      - home_agl:/hal
      - home_agl:/home/${_AGL}
      - home_dvl:/hel
      - home_dvl:/home/${_DVL}
      - home_r00t:/r00t
      - home_r00t:/home/r00t
    depends_on:
        base:
            # Wait for the ownership to change
          condition: service_completed_successfully

    labels:
      com.dvlp_skel.description: "-build skeleton"
  skel:
    # user: devel
    extends: skel-build
    working_dir: /hel
    build:
      target: dvlp_skel
    volumes:
      - repo:/dvlw
      - repo:/r00t/dvlw
      - repo:/home/r00t/dvlw
      - repo:/hal/dvlw
      - repo:/home/{${_AGL}/dvlw
      - repo:/hel/dvlw
      - repo:/home/${_DVL}/dvlw
    depends_on:
      skel-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.dvlp_skel.description: "skeleton"
  bare:
    entrypoint: /bin/bash -c
    command:
      - sleep infinity
    # user: devel
    extends: skel-build-lite
    working_dir: /hel
    restart: on-failure
    tty: true
    # entrypoint: /bin/bash -c
    # entrypoint: ["/bin/bash", "-l", "-c"]
    # # # entrypoint: ["bash -i chroot --userspec=dvl:dvl /fs"]
    # command: ["-it", "chroot --userspec=dvl:dvl /fs"]
    # command:  ["bash -i chroot --userspec=dvl:dvl /fs"]
    # cap_add:
    #     - SYS_CHROOT
    privileged: true
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-bare
    # extends: skel
    build:
      context: .
      target: dvlp_bare
    depends_on:
      skel-build-lite:
        # Wait for the ownership to change
        condition: service_completed_successfully
    init: true
    # entrypoint: ["sudo chown -R agl:halo /home/${_AGL}/dvlw"]
    # entrypoint: /bin/bash -c
    # # entrypoint: ["sudo chown -R agl:halo /home/${_AGL}/dvlw"]
    # # command:
    # #   # - sudo chown -R agl:halo /halo/hal/dvlw
    # #   # - chown -R dvl:hell 
    # #   # - sudo chown -R dvl:hell /hell
    # #   - sleep infinity
    # #   # - -c
    # #   # - sudo
    # #   # - chown 
    # #   # - -R 
    # #   # - agl:halo 
    # #   # - /halo/hal/dvlw
    # volumes:
    #   - repo-lite:/dvlw
    #   - home_agl:/hal
    #   - home_agl:/home/${_AGL}
    #   - home_dvl:/hel
    #   - home_dvl:/home/${_DVL}
    #   - home_r00t:/r00t
    #   - home_r00t:/home/r00t
    # #   # - repo-lite:/halo/hal/dvlw
    # #   # - repo-lite:/halo/dvlw
    # #   - repo-lite:/hal/dvlw
    # #   - repo-lite:/home/${_AGL:-$_AGL_USR}/dvlw

    # #   # - repo-lite:/hell/hel/dvlw
    # #   # - repo-lite:/hell/dvlw
    # #   - repo-lite:/hel/dvlw
    # #   - repo-lite:/home/${_DVL:-$_DVL_USR}/dvlw

    # #   # - repo-lite:/r00t/dvlw
    # #   - repo-lite:/r00t/dvlw
    # #   - repo-lite:/home/r00t/dvlw

    # #   # - root:/
    # #   # - root:/root
    # #   # - home_r00t:/r00t
    # #   - home_r00t:/home/r00t

    # #   # - root:/hell
    # #   - home_dvl:/hel
    # #   # - home_dvl:/hell/hel
    # #   - home_dvl:/home/${_DVL:-$_DVL_USR}

    # #   # - root:/halo
    # #   - home_agl:/hal
    # #   # - home_agl:/halo/hal
    # #   - home_agl:/home/${_AGL:-$_AGL_USR}

    # #   - mnt-data:/mnt/data

    # #   - dls:/mnt/data/dls

    # #   - dls_r00t:/dls
    # #   # - dls_r00t:/root/dls
    # #   # - dls_r00t:/r00t/dls
    # #   - dls_r00t:/home/r00t/dls

    # #   - dls_agl:/hal/dls
    # #   # - dls_agl:/halo/dls
    # #   # - dls_agl:/halo/hal/dls
    # #   - dls_agl:/home/${_AGL:-$_AGL_USR}/dls

    # #   - dls_dvl:/hel/dls
    # #   # - dls_dvl:/hell/dls
    # #   # - dls_dvl:/hell/hel/dls
    # #   - dls_dvl:/home/${_DVL:-$_DVL_USR}/dls
    labels:
      com.devels-playground.description: "basics + git"
  git-lite:
    extends: bare
    #   # - sudo cp -rf /lib /usr /mnt /bin /opt /lib64 /tmp /home /sbin /media /etc /root /boot /var /fs
    #   - git config --global --add safe.directory /dvlw && (git submodule update --init --progress dvlp  ||     git submodule update --init --progress --force --rebase --  dvlp/kernels)
    # image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-git-lite
    # extends: skel
    build:
      context: .
      target: dvlp_git-lite
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-git-lite
    # volumes:
    #   - repo-lite:/dvlw
    #   - repo:/dvlw
    #   - home_agl:/hal
    #   - home_agl:/home/${_AGL}
    #   - home_dvl:/hel
    #   - home_dvl:/home/${_DVL}
    #   - home_r00t:/r00t
    #   - home_r00t:/home/r00t
    # #   - repo-lite:/halo/hal/dvlw
    # #   - repo-lite:/halo/dvlw
    # #   - repo-lite:/hal/dvlw
    # #   - repo-lite:/home/${_AGL}/dvlw

    # #   - repo-lite:/hell/hel/dvlw
    # #   - repo-lite:/hell/dvlw
    # #   - repo-lite:/hel/dvlw
    # #   - repo-lite:/home/${_DVL}/dvlw

    # #   - repo-lite:/r00t/dvlw
    # #   - repo-lite:/root/dvlw
    # #   - repo-lite:/home/r00t/dvlw
    labels:
      com.devels-playground.description: "basics + git"

  git:
    entrypoint: /bin/bash -c
    command:
      - sleep infinity
    # user: devel
    extends: skel-build
    working_dir: /hel
    restart: on-failure
    tty: true
    # entrypoint: /bin/bash -c
    # entrypoint: ["/bin/bash", "-l", "-c"]
    # # # entrypoint: ["bash -i chroot --userspec=dvl:dvl /fs"]
    # command: ["-it", "chroot --userspec=dvl:dvl /fs"]
    # command:  ["bash -i chroot --userspec=dvl:dvl /fs"]
    # cap_add:
    #     - SYS_CHROOT
    privileged: true
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dvlp_git
    depends_on:
      skel:
        # Wait for the ownership to change
        condition: service_completed_successfully
    # volumes:
    #   - repo:/dvlw
      # - home_agl:/hal
      # - home_agl:/home/${_AGL}
      # - home_dvl:/hel
      # - home_dvl:/home/${_DVL}
      # - home_r00t:/r00t
      # - home_r00t:/home/r00t
      # - repo:/hal/dvlw
      # - repo:/home/${_AGL:-$_AGL_USR}/dvlw
      # - repo:/hel/dvlw
      # - repo:/home/${_DVL:-$_DVL_USR}/dvlw
      # - repo:/r00t/dvlw
      # - repo:/home/r00t/dvlw
    labels:
      com.devels-playground.description: "basics + git"

  python-build:
    extends: skel-build
    build:
      context: .
      target: dvlp_python-build
    labels:
      com.devels-playground.description: "basics + git"
  python-build-lite:
    extends: skel-build-lite
    build:
      context: .
      target: dvlp_python-build-lite
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.devels-playground.description: "basics + git"
  python-lite:
    extends: git-lite
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-py-lite
    build:
      context: .
      target: dvlp_python-lite
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_started
    labels:
      com.devels-playground.description: "basics + git"
  python:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-py
    build:
      context: .
      target: dvlp_python
    depends_on:
      python-build:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.devels-playground.description: "basics + git"
  msdot-lite:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-msdot-lite
    build:
      context: .
      target: dvlp_msdot-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell"
  msdot:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-msdot
    build:
      context: .
      target: dvlp_msdot
    labels:
      com.devels-playground.description: "basics + git + powerhell"
  dind:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-dind
    build:
      context: .
      target: dvlp_dind
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker"
  dind-lite:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-dind-lite
    build:
      context: .
      target: dvlp_dind-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  kernel-builder:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-basic-wsl-kernel-builder
    build:
      context: .
      target: dvlp_kernel-builder
      # args:
      #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  # basic-wsl-zfs-kernel-builder:
  #   extends: bare
  #   image: kindtek/${HUB_REPO:-devels-playground}:basic-wsl-zfs-kernel-builder
  #   build:
  #     context: .
  #     target: dvlp_basic-wsl-zfs-kernel-builder
  #     # args:
  #     #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
  #   labels:
  #     com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  # stable-wsl-zfs-kernel-builder:
  #   extends: bare
  #   image: kindtek/${HUB_REPO:-devels-playground}:stable-wsl-zfs-kernel-builder
  #   build:
  #     context: .
  #     # target: dvlp_stable-wsl-zfs-kernel-builder
  #     # args:
  #     #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
  #   labels:
  #     com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  # latest-rc-wsl-zfs-kernel-builder:
  #   extends: bare
  #   image: kindtek/${HUB_REPO:-devels-playground}:latest-rc-wsl-zfs-kernel-builder
  #   build:
  #     context: .
  #     target: dvlp_latest-rc-wsl-zfs-kernel-builder
  #     # args:
  #     #   - CONFIG_FILE=${CONFIG_FILE:-dvlw/dvlp/kernels/linux/x86/generic/.config_wsl0}
  #   labels:
  #     com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  gui-lite:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-gui
    build:
      context: .
      target: dvlp_gui-lite
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  gui:
    extends: git
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-gui
    user: ${_AGL}
    # entrypoint:
    #   - /bin/bash
    #   - -c
    #   - bash /home/${_DVL}/start-kde.sh
    entrypoint: /bin/bash -c
    command: bash /home/${_AGL}/start-kde.sh
    build:
      context: .
      target: dvlp_gui
      args:
        - _AGL=${_AGL_USR:-$_AGL}
        - _DVL=${_DVL_USR:-$_DVL}
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  gui-plus:
    extends: gui
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-gui-plus
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"
  cuda:
    extends: gui
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-cuda
    build:
      context: .
      target: dvlp_cuda
      labels:
        com.dvlp_cuda.description: "basics + git + powerhell + docker + gui + cuda"

  cuda-plus:
    extends: gui
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-cuda-plus
    build:
      context: .
      target: dvlp_cuda-plus
      labels:
        com.dvlp_cuda.description: "basics + git + powerhell + docker + gui + cuda"
  world:
    build:
      context: .
      target: dvlp_world
      args:
        - _AGL=${_AGL_USR:-$_AGL}
        - _DVL=${_DVL_USR:-$_DVL}
      labels:
        com.dvlp_cuda.description: "hello world"
    volumes:
      - world_dvl:/g0d/r00t/hell
      - world_agl:/g0d/r00t/halo
      # - world_r00t:/g0d/r00t/halo
      # - world_g0d:/g0d/r00t/halo
  world-bare:
    extends: world
    build:
      
      target: dvlp_world-bare

  worlds:
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-worlds
    entrypoint: /bin/bash -c
    command:
      - sleep infinity
    build:
      context: .
      target: dvlp_worlds
      args:
        - _AGL=${_AGL_USR:-$_AGL}
        - _DVL=${_DVL_USR:-$_DVL}
        - WORLDS=gui
      labels:
        com.dvlp_cuda.description: "hello worlds"
    volumes:
      - world_dvl:/g0d/r00t/hell
      - world_agl:/g0d/r00t/halo
      - world_agl:/g0d/r00t
      - world_agl:/g0d
    depends_on:
      world:
        condition: service_completed_successfully
  worlds-gui-plus:
    extends: worlds
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-world-gui
    build:
      target: dvlp_worlds
      args:
        - WORLDS=gui-plus
  worlds-bare:
    extends: worlds
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-worlds-bare
    build:
      args:
        - WORLDS=bare
  worlds-gui-lite:
    extends: worlds
    image: kindtek/${HUB_REPO:-devels-playground}:ubuntu-worlds-gui-lite
    build:
      args:
        - WORLDS=gui-lite
volumes:
  root:
  root_dvl:
  root_agl:
  root_r00t:

  mnt-data:

  dls:
  dls_dvl:
  dls_agl:
  dls_r00t:

  home_dvl:
  home_agl:
  home_r00t:

  repo:
  repo-lite:
  repo_agl:
  repo_dvl:
  repo_r00t:

  world_dvl:
  world_agl:
  world_r00t:
  world_g0d:

networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
