version: "3.9"
name: devels-play-ubuntu
services:

  initialize:
    # Need a user priviliged enough to chown
    build:
      context: .
      target: dplay_init
    init: true
    command:
      - bin/bash
      - -c
      - export _AGL=${_AGL:-agl}
      - export _HALOS=${_HALOS:-halos}
      - ln -s /home/${_AGL:-agl} /tmp/${_AGL:-agl}
      - ln -s /home/dvl /tmp/dvl
      - mkdir -p /mnt/data
      - ln -s /mnt/data /tmp/data
    # command: echo something

  chown-hal:
    # Need a user priviliged enough to chown
    user: ${_AGL:-agl}
    # Specify the wings in question
    group_add:
      - ${_HALOS:-halos}
    build:
      context: .
      target: dplay_hal
    depends_on:
      initialize:
        # Wait for the groups to be added
        condition: service_completed_successfully
    init: true
    volumes:
      - hal-data:/tmp/${_AGL:-agl}
    command: sudo chown -R ${_AGL:-agl}:${_HALOS:-halos} /tmp/${_AGL:-agl}

  chown-hel:
    # Need a user priviliged enough to chown
    user: dvl
    # Specify the wings in question
    group_add:
      - horns
    build:
      context: .
      target: dplay_hel
    depends_on:
      initialize:
        # Wait for groups to be added
        condition: service_completed_successfully
    init: true
    volumes:
      - hel-data:/tmp/dvl
    command: chown -R dvl:horns /tmp/dvl

  data:
    user: ${_AGL:-agl}
    group_add:
      - ${_HALOS:-halos}
    build:
      context: .
      target: dplay_data
    depends_on:
      chown-hel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      chown-hal:
        # Wait for the ownership to change
        condition: service_completed_successfully
    init: true
    volumes:
      - mnt-data:/tmp/data
  skel:
    extends: data
    user: ${_AGL:-agl}
    build:
      context: .
      target: dplay_skel
      args:
        - _AGL=${_AGL:-agl}
        - _HALOS=${_HALOS:-halos}
      # network: ${COMPOSE_PROJECT_NAME}_default
    init: true
    volumes:
      - hel-data:/home/dvl
      - hal-data:/home/${_AGL:-agl}
      - mnt-data:/mnt/data
    depends_on:
      data:
        # Wait for the ownership to change
        condition: service_completed_successfully
    labels:
      com.dplay_skel.description: "skeleton"

  git:
    # owner/group becomes owner of hel-data volume
    extends: data
    user: dvl
    privileged: true
    entrypoint:
      - sleep
      - infinity
    image: kindtek/dplay:ubuntu-git
    # extends: skel
    build:
      context: .
      target: dplay_git
      args:
        - _AGL=${_AGL:-agl}
    depends_on:
      chown-hel:
        # Wait for the ownership to change
        condition: service_completed_successfully
      chown-hal:
        # Wait for the ownership to change
        condition: service_completed_successfully
      data:
        # Wait for the ownership to change
        condition: service_completed_successfully
    volumes:
      - hel-data:/home/dvl
      - hal-data:/home/${_AGL:-agl}
      - /mnt/data
    labels:
      com.devels-play.description: "basics + git"

  python:
    extends: git
    image: kindtek/dplay:ubuntu-py
    build:
      context: .
      target: dplay_python
    labels:
      com.devels-play.description: "basics + git + powerhell"

  msdot:
    extends: git
    image: kindtek/dplay:ubuntu-msdot
    build:
      context: .
      target: dplay_msdot
    labels:
      com.devels-play.description: "basics + git + powerhell"

  dind:
    extends: git
    image: kindtek/dplay:ubuntu-dind
    build:
      context: .
      target: dplay_dind
    labels:
      com.devels-play.description: "basics + git + powerhell + docker"

  kernel:
    extends: git
    image: kindtek/dplay:ubuntu-kernel
    build:
      context: .
      target: dplay_kernel
    labels:
      com.devels-play.description: "basics + git + powerhell + docker + kernel"

  kernel_phat:
    extends: git
    image: kindtek/dplay:ubuntu-kernel-phat
    build:
      context: .
      target: dplay_kernel-phat
    labels:
      com.devels-play.description: "basics + git + powerhell + docker + kernel"

  gui:
    extends: git
    image: kindtek/dplay:ubuntu-gui
    build:
      context: .
      target: dplay_gui
    labels:
      com.devels-play.description: "basics + git + powerhell + docker + kernel + gui"

  gui_phat:
    extends: git
    image: kindtek/dplay:ubuntu-gui-phat
    build:
      context: .
      target: dplay_gui-phat
    labels:
      com.devels-play.description: "basics + git + powerhell + docker + kernel + gui"
  # cuda:
  #   extends: gui
  #   image: kindtek/dplay:ubuntu-cuda
  #   build:
  #     context: .
  #     target: dplay_cuda
  #     args:
  #       - _AGL=${_AGL:-agl}
  #     labels:
  #       com.dplay_cuda.description: "basics + git + powerhell + docker + gui + cuda"

  # cuda_phat:
  #   extends: gui
  #   image: kindtek/dplay:ubuntu-cuda-phat
  #   build:
  #     context: .
  #     target: dplay_cuda-phat
  #     args:
  #       - _AGL=${_AGL:-agl}
  #     labels:
  #       com.dplay_cuda.description: "basics + git + powerhell + docker + gui + cuda"

volumes:
  hel-data:
  hal-data:
  mnt-data:


networks:
  "${COMPOSE_PROJECT_NAME}_default":
    driver: overlay
    attachable: true
