version: "3.9"
name: devels-playground-kali
services:
  base-template:
    build:
      context: .
      args:
      - _ARCH=${_ARCH}
      - _ARCH_VENDOR=${_ARCH_VENDOR}
      - __ARCH__VENDOR=${__ARCH__VENDOR}
      - DOCKER_HUB_IMG=${HUB_IMG}
      - DOCKER_HUB_REPO=${HUB_REPO}
    env_file:
      - .env
    environment:
      - _ARCH=${_ARCH}
      - _ARCH_VENDOR=${_ARCH_VENDOR}
      - __ARCH__VENDOR=${__ARCH__VENDOR}
      - DOCKER_HUB_IMG=${HUB_IMG}
      - DOCKER_HUB_REPO=${HUB_REPO}
    restart: on-failure
    cap_add:
      - AUDIT_WRITE
      - SYS_CHROOT
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - FOWNER
      - MKNOD
      - NET_RAW
      - SETGID
      - SETUID
      - SETFCAP
      - SETPCAP
      - NET_BIND_SERVICE
    volumes:
      - repo_agl:/repos/dvlw
      - repo_agl:/r00t/dvlw
      - repo_agl:/home/r00t/dvlw
      - repo_agl:/hal/dvlw
      - repo_agl:/home/${_AGL}/dvlw
      - repo_dvl:/hel/dvlw
      - repo_dvl:/home/${_DVL}/dvlw
      - mnt-data:/mnt/data
      - home_agl:/hal
      - home_agl:/home/${_AGL}
      - home_dvl:/hel
      - home_dvl:/home/${_DVL}
      - home_r00t:/r00t
      - home_r00t:/home/r00t
      - dls:/dls

  build-repo-builder:
    # command: /bin/bash -c apt-get update -y && apt-get upgrade -y
    build:
      context: .
      target: dvlp_repo-builder
    env_file:
      - .env

  build-repo-image-builder:
    extends: build-repo-builder
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:repo-builder
    depends_on:
      build-repo-builder:
        condition: service_completed_successfully

  repo-image-builder:
    extends: build-repo-image-builder
    build:
      context: ""
      target: ""

  build-repo:
    build:
      context: .
      target: dvlp_repo
      no_cache: true
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:repo
    entrypoint: /bin/bash -c echo 'helloworld'
    command:
      - echo 'helloworld'
    env_file:
      - .env
    volumes:
      - repo_agl:/repos/dvlw
      - repo_agl:/r00t/dvlw
      - repo_agl:/home/r00t/dvlw
      - repo_agl:/hal/dvlw
      - repo_agl:/home/${_AGL}/dvlw
      - repo_dvl:/hel/dvlw
      - repo_dvl:/home/${_DVL}/dvlw

  get-kernel:
    build:
      context: .
      target: dvlp_get-kernel

  build-repo-kernel:
    extends: build-repo
    build:
      target: dvlp_repo-kernel

  build-r00t:
    build:
      target: dvlp_base-r00t-volumes-built
    env_file:
      - .env

  build-angel:
    build:
      target: dvlp_base-angel-volumes-built
    env_file:
      - .env

  build-devel:
    build:
      target: dvlp_base-devel-volumes-built
    env_file:
      - .env

  build-vols:
    extends: base-template
    tty: false
    init: true
    entrypoint: /bin/bash -c echo 'helloworld entry'
    command:
      - /bin/bash -c echo 'helloworld command'
    build:
      target: dvlp_base-volumes-builder
      no_cache: true
    volumes:
      - repo_agl:/repos/dvlw
      - repo_agl:/r00t/dvlw
      - repo_agl:/home/r00t/dvlw
      - repo_agl:/hal/dvlw
      - repo_agl:/home/${_AGL}/dvlw
      - repo_dvl:/hel/dvlw
      - repo_dvl:/home/${_DVL}/dvlw
      - mnt-data:/mnt/data
      - home_agl:/hal
      - home_agl:/home/${_AGL}
      - home_dvl:/hel
      - home_dvl:/home/${_DVL}
      - home_r00t:/r00t
      - home_r00t:/home/r00t
      - dls:/dls

  build-vols-kernel:
    extends: build-vols
    build:
      target: dvlp_base-kernel-volumes-builder
    volumes_from:
      - build-vols
    volumes:
      - repo_agl-kernel:/repos/dvlw/dvlp/kernels
      - repo_agl-kernel:/r00t/dvlw/dvlp/kernels
      - repo_agl-kernel:/home/r00t/dvlw/dvlp/kernels
      - repo_agl-kernel:/hal/dvlw/dvlp/kernels
      - repo_agl-kernel:/home/${_AGL}/dvlw/dvlp/kernels
      - repo_dvl-kernel:/hel/dvlw/dvlp/kernels
      - repo_dvl-kernel:/home/${_DVL}/dvlw/dvlp/kernels

  vols:
    extends: base-template
    entrypoint: ["/bin/bash", "echo 'helloworldentry'"]
    command: ["/bin/bash", "echo 'helloworld'command"]
    volumes_from:
      - build-vols

  vols-kernel:
    extends: vols
    volumes_from:
      - build-vols-kernel

  build-skel:
    init: true
    extends: base-template
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-skel
    build:
      target: dvlp_base-skel
    restart: on-failure
    depends_on:
      build-vols:
        condition: service_completed_successfully
      build-vols-kernel:
        condition: service_completed_successfully

  build-skel-image:
    extends: build-skel
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-skel
    depends_on:
      skel-image:
        condition: service_completed_successfully

  skel-image:
    extends: build-skel-image
    build:
      target: ""
      context: ""
    # depends_on:
    #   build-skel-image:
    #     condition: service_completed_successfully

  build-k-home-win:
    build:
      target: dvlp_k-home-win
      no_cache: true
    env_file:
      - .env

  build-k-home-nix:
    extends: build-k-home-win
    build:
      target: dvlp_k-home-nix-angel

  build-k-home-nix-angel:
    extends: build-k-home-nix

  build-k-home-nix-devel:
    extends: build-k-home-nix
    build:
      target: dvlp_k-home-nix-devel

  build-k-home-nix-r00t:
    extends: build-k-home-nix
    build:
      target: dvlp_k-home-nix-r00t

  build-base-builder:
    extends: build-skel
    tty: false
    build:
      target: dvlp_base-builder
    depends_on:
      skel-image:
        condition: service_completed_successfully
    labels:
      com.dvlp_base.description: "-build skeleton"
    volumes_from:
      - build-vols

  build-base-image-builder:
    extends: build-base-builder
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-build
    depends_on:
      build-base-builder:
        condition: service_completed_successfully

  base-image-builder:
    extends: build-base-image-builder
    build:
      target: ""
      context: ""

  build-base-kernel-builder:
    extends: build-base-builder
    tty: false
    build:
      target: dvlp_base-kernel-builder
    depends_on:
      skel-image:
        condition: service_completed_successfully
      build-vols-kernel:
        condition: service_completed_successfully
    labels:
      com.dvlp_base.description: "-build skeleton"
    volumes_from:
      - build-vols-kernel

  build-base-kernel-image-builder:
    extends: build-base-kernel-builder
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-build-kernel
    depends_on:
      build-base-kernel-builder:
        condition: service_completed_successfully

  base-kernel-image-builder:
    extends: build-base-kernel-builder
    build:
      target: ""
      context: ""
    depends_on:
      build-base-kernel-image-builder:
        condition: service_completed_successfully

  make-kernel:
    extends: build-base-kernel-builder
    entrypoint: /bin/bash -c echo 'helloworld'
    # entrypoint: /bin/bash  [ ! -f build-export-kernel.sh ] || bash build-export-kernel.sh "${KERNEL_TYPE}" "${CONFIG_FILE}" "${KERNEL_FEATURE}" "${DOCKER_BUILD_TIMESTAMP}"
    command:
      - tail -F /dev/null
    build:
      context: .
      target: dvlp_base-kernel
      no_cache: false
      args:
        - KERNEL_TYPE=stable
        - KERNEL_FEATURE=zfs
    environment:
      - KERNEL_TYPE=stable
      - KERNEL_FEATURE=zfs
      - CONFIG_FILE=${CONFIG_FILE}
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  make-kernel-cached:
    extends: make-kernel
    build:
      context: .
      target: dvlp_base-kernel
      no_cache: false
    depends_on:
      vols-kernel:
        condition: service_started

  make-kernel-basic:
    extends: make-kernel
    build:
      target: dvlp_base-kernel
      args:
        - KERNEL_TYPE=basic
        - KERNEL_FEATURE=
    environment:
      - KERNEL_TYPE=basic
      - KERNEL_FEATURE=
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  make-kernel-basic-zfs:
    extends: make-kernel
    build:
      target: dvlp_base-kernel
      args:
        - KERNEL_TYPE=basic
        - KERNEL_FEATURE=zfs
    environment:
      - KERNEL_TYPE=basic
      - KERNEL_FEATURE=zfs
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  make-kernel-stable:
    extends: make-kernel
    build:
      target: dvlp_base-kernel
      args:
        - KERNEL_TYPE=stable
        - KERNEL_FEATURE=
    environment:
      - KERNEL_TYPE=stable
      - KERNEL_FEATURE=
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  make-kernel-stable-zfs:
    extends: make-kernel
    build:
      target: dvlp_base-kernel
      args:
        - KERNEL_TYPE=stable
        - KERNEL_FEATURE=zfs
    environment:
      - KERNEL_TYPE=stable
      - KERNEL_FEATURE=zfs
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  make-kernel-latest-zfs:
    extends: make-kernel
    build:
      target: dvlp_base-kernel
      args:
        - KERNEL_TYPE=latest
        - KERNEL_FEATURE=zfs
    environment:
      - KERNEL_TYPE=latest
      - KERNEL_FEATURE=zfs
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  make-kernel-latest:
    extends: make-kernel
    build:
      target: dvlp_base-kernel
      args:
        - KERNEL_TYPE=latest
        - KERNEL_FEATURE=
    environment:
      - KERNEL_TYPE=latest
      - KERNEL_FEATURE=
    depends_on:
      build-base-kernel-image-builder:
        condition: service_started
    volumes_from:
      - build-vols-kernel

  made-kernel:
    extends: make-kernel
    build:
      target: dvlp_made-kernel
    entrypoint: /bin/bash -c echo 'helloworld entry'
    command:
      - /bin/bash -c echo 'helloworld command'
    depends_on:
      make-kernel:
        condition: service_completed_successfully
      build-vols-kernel:
        condition: service_completed_successfully

  made-kernel-cached:
    extends: made-kernel
    build:
      context: .
      target: dvlp_made-kernel
      no_cache: false
    depends_on:
      skel-image:
        condition: service_completed_successfully
      vols-kernel:
        condition: service_completed_successfully

  build-base:
    extends: build-base-builder
    tty: true
    entrypoint: /bin/bash -c echo 'helloworld entry'
    command:
      - /bin/bash -c echo 'helloworld command'
    expose:
      - "3390"
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-base
    build:
      target: dvlp_base
      args:
        - _AGL=${_AGL:-agl}
        - _DVL=${_DVL:-dvl}
    # entrypoint: /bin/bash -c
    # command:
    #   - tail -F /dev/null
    depends_on:
      build-base-builder:
        condition: service_completed_successfully
    labels:
      com.dvlp_base.description: "-build skeleton"

  build-base-kernel:
    extends:
      build-base-kernel-builder
    depends_on:
      build-base-kernel-builder:
        condition: service_completed_successfully

  bare:
    extends: build-base
    entrypoint: /bin/bash -c
    command:
      - tail -F /dev/null
    build:
      context: .
      target: dvlp_bare
    labels:
      com.devels-playground.description: "basics + git"
    volumes:
      - win_c:/mnt/c
      - win_n:/mnt/n
      - mnt-data:/mnt/data
    env_file:
      - .env
  cli:
    extends: bare
    build:
      target: dvlp_cli
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-cli${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    labels:
      com.devels-playground.description: "basics + git"
    depends_on:
      build-base:
        condition: service_completed_successfully
    volumes:
      - home_agl:/mnt/n/hal
      - home_dvl:/mnt/n/hel
    volumes_from:
      - vols
      - bare

  cli-kernel:
    extends: bare
    entrypoint: /bin/bash -c
    command:
      - tail -F /dev/null
    restart: on-failure
    tty: true
    privileged: true
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-cli${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    build:
      target: dvlp_cli
      args:
        - KERNEL_TYPE=stable
        - KERNEL_FEATURE=zfs
    environment:
      - KERNEL_TYPE=stable
      - KERNEL_FEATURE=zfs
    depends_on:
      build-base-kernel:
        condition: service_completed_successfully
    volumes:
      - home_agl:/mnt/n/hal
      - home_dvl:/mnt/n/hel
    volumes_from:
      - vols-kernel
      - bare

  # build-scan:
  #   entrypoint: /bin/bash -c
  #   command:
  #     - sleep infinity
  #   # user: ${_AGL}
  #   extends: build-base
  #   working_dir: /hal
  #   restart: on-failure
  #   tty: true
  #   privileged: true
  #   image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-scan-build${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
  #   # extends: kernel
  #   build:
  #     context: .
  #     target: dvlp_scan-build
  #   depends_on:
  #     build-base:
  #       condition: service_completed_successfully
  #   labels:
  #     com.devels-playground.description: "basics + git"

  scan:
    entrypoint: /bin/bash -c
    command:
      - sleep infinity
    # user: ${_AGL}
    # extends: scan-build
    privileged: true
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-scan${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    build:
      context: .
      target: dvlp_base-scan
    labels:
      com.devels-playground.description: "basics + git"

  cli-goodies:
    extends: cli
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-cli${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}-goodies
    build:
      context: .
      target: dvlp_cli-goodies
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker"
    volumes_from:
      - vols
      - bare
      - cli

  cli-kernel-goodies:
    extends: cli-kernel
    build:
      target: dvlp_cli-goodies
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-cli${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}-goodies
    labels:
      com.devels-playground.description: "basics + git"
    volumes_from:
      - vols-kernel
      - bare
      - cli-kernel

  # cli-goodies-lite:
  #   extends: cli
  #   image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-dind-lite${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
  #   build:
  #     context: .
  #     target: dvlp_cli-goodies-lite
  #   labels:
  #     com.devels-playground.description: "basics + git + powerhell + docker + kernel"
  # cli-goodies-lite-kernel:
  #   extends: cli-kernel
  #   build:
  #     target: dvlp_cli-goodies-lite
  #   image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-dind-lite${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
  # depends_on:
  #   cli-goodies-lite:
  #     condition: service_completed_successfully
  # labels:
  #   com.devels-playground.description: "basics + git"

  gui:
    extends: cli
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-gui${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    build:
      context: .
      target: dvlp_gui
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"

  gui-kernel:
    extends: cli-kernel
    build:
      target: dvlp_gui
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-gui${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    labels:
      com.devels-playground.description: "basics + git"

  gui-goodies:
    extends: cli
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-gui${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}-goodies
    build:
      context: .
      target: dvlp_gui-goodies
    labels:
      com.devels-playground.description: "basics + git + powerhell + docker + kernel + gui"

  gui-kernel-goodies:
    extends: cli-kernel
    build:
      target: dvlp_gui-goodies
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-gui-kernel${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}-goodies
    labels:
      com.devels-playground.description: "basics + git"

  gui-goodies-cuda:
    extends: cli
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-gui-goodies-cuda${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    build:
      context: .
      target: dvlp_gui-goodies-cuda
      labels:
        com.devels-playground.description: "basics + git + powerhell + docker + gui + cuda"

  gui-goodies-kernel-cuda:
    extends: gui-kernel
    image: ${HUB_REPO:-kindtek}/${HUB_IMG:-devels-playground}:kali-gui-goodies-cuda-kernel${KERNEL_TYPE:+-kernel}${KERNEL_TYPE:+-$__ARCH__VENDOR}
    labels:
      com.devels-playground.description: "basics + git"

volumes:
  root:
  root_dvl:
  root_agl:
  root_r00t:

  mnt-data:

  dls: 
  # dls_dvl:
  # dls_agl:
  # dls_r00t:

  home_dvl:
  home_agl:
  home_r00t:

  repo_agl:
  repo_agl-kernel:
  repo_dvl:
  repo_dvl-kernel:
  repo_r00t:
  
  host_mac:
  host_win:
  host_nix:
  win_c:
  win_n:
# networks:
#   "${COMPOSE_PROJECT_NAME}_default":
#     driver: overlay
#     attachable: true
